### PR TITLE
Fixed UI

### LINKED ISSUE #49: Game's graphic flickering
The game can still play, but the game has severe flickering issues.

Screenshot 2024-08-16 at 9 13 35 AM

### PR DESCRIPTION
**Pull request by kemurayama**
This PR closes #49.

### CODE REVIEW

**Comment by kemurayama** [comment]
Specifically, I removed particles on UI.

**Comment by kemurayama** [comment]
image

**Comment by kemurayama** [comment]
Hi @govargo 

Could you review this PR ?

**Review by govargo — APPROVED** [review]
Thank you!
#49 was big blocker for playing games.

**Pull request merged**
